services:
  - type: web
    name: Nutrify
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: OPENROUTER_API_KEY
        fromService:
          type: secret
          name: openrouter-api-key